apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-app-deployment
  labels:
    app: healthcare-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: healthcare-app
  template:
    metadata:
      labels:
        app: healthcare-app
    spec:
      containers:
      - name: healthcare-app-container
        image: gayatrihedau/myproject1
        ports:
        - containerPort: 8082
