apiVersion: v1
kind: Service
metadata:
  name: healthcare-app-service
spec:
  selector:
    app: healthcare-app # Select pods with this label
  ports:
    - protocol: TCP
      port: 80  # The port on the service
      targetPort: 8082 # The port on the pod
  type: LoadBalancer # Expose the service via a cloud provider's load balancer
