apiVersion: v1
kind: Service
metadata:
  name: healthcare-app-service
  labels:
    app: healthcare-app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "classic"  # Use AWS Classic Load Balancer (ELB)
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8082
    protocol: TCP
  selector:
    app: healthcare-app
